apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins-ns
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      # initContainers:
      # - name: install-docker
      #   image: docker:stable
      #   command: ["cp", "/usr/local/bin/docker", "/data/docker"]    
      #   volumeMounts:
      #   - name: docker
      #     mountPath: "/data"
      containers:
        - name: jenkins
          image: docker.io/712199425/jenkins:latest
          ports:
            - containerPort: 8080
          # securityContext:  # Add securityContext for the container
          #   runAsUser: 0  # Run as root user
          volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_home
          # - name: "docker"
          #   mountPath: "/usr/local/bin/docker"
          # - name: kubectl
          #   subPath: "kubectl"
          #   mountPath: "/usr/local/bin/kubectl"
          - name: docker
            mountPath: "/var/run/docker.sock"  
      volumes:
        - name: jenkins-vol
          emptyDir: {}
        # - name: docker
        #   emptyDir: {}
        - name: docker
          hostPath:
            path: /var/run/docker.sock
        #     type: ""
        # - name: kubectl
        #   emptyDir: {}
        
